use DataSoup
go
SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS ON 
GO
if exists (select * from dbo.sysobjects where id = object_id(N'[osi].[IrsDetail_vLoad]') and OBJECTPROPERTY(id, N'IsView') = 1)
drop view [osi].[IrsDetail_vLoad]
GO
setuser N'osi'
GO
create view osi.IrsDetail_vLoad
as
/*
————————————————————————————————————————————————————————————————————————————————
			© 2000-08 • Texans Credit Union • All rights reserved.
————————————————————————————————————————————————————————————————————————————————
Developer:	Paul Hunter
Created  :	10/23/2008
Purpose  :	Used by the IRS Files process for bulk loading of the raw IRS File
			generated by OSI.
History  :
  Date		Developer		Description
——————————	——————————————	————————————————————————————————————————————————————
————————————————————————————————————————————————————————————————————————————————
*/

select	Detail
from	osi.IrsDetail
GO
setuser
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO