use DataSoup
go
if exists (select * from dbo.sysobjects where id = object_id(N'[legacy].[Member]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [legacy].[Member]
GO
CREATE TABLE [legacy].[Member] (
	[Period] [int] NOT NULL ,
	[MemberID] [int] NOT NULL ,
	[MemberNumber] [bigint] NOT NULL ,
	[BranchID] [smallint] NULL ,
	[MemberName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[JointName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Address1] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Address2] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[City] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Zip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PrimaryPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SecondaryPhone] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[EMail] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IsEmployee] [tinyint] NULL ,
	[SSN] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[HasDirectDeposit] [tinyint] NULL ,
	[Birthdate] [datetime] NULL ,
	[IsForeignAddress] [tinyint] NULL ,
	[GenderCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AccountOwnerCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SecondarySSN] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[JoinedOn] [datetime] NULL ,
	[HasLoanCollection] [tinyint] NULL ,
	[ATMCardCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ShareDraftCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LoanCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CDCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LoanCurrentCount] [smallint] NULL ,
	[SpecialHandlingCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[StatusCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MailCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[HasDormantAccount] [tinyint] NULL ,
	[UserCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IsDeceased] [tinyint] NULL ,
	[OwnerCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastContactedOn] [datetime] NULL ,
	[CreditBureauDate] [datetime] NULL ,
	[MiscFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AlternateAddressCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[HasCreditCardAccount] [tinyint] NULL ,
	[AllDisclosureOptionsCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[HasDisclosureOption1] [tinyint] NULL ,
	[HasDisclosureOption2] [tinyint] NULL ,
	[HasDisclosureOption3] [tinyint] NULL ,
	[HasDisclosureOption4] [tinyint] NULL ,
	[HasDisclosureOption5] [tinyint] NULL ,
	[IsSelfService] [tinyint] NULL ,
	[HasOFAC] [tinyint] NULL ,
	[eMailCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastACHDirectDepositOn] [datetime] NULL ,
	[BankruptcyScore] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ThirdSSN] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Employer] [varchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MaritalStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DependentCount] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[POSCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Department] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[EmploymentDate] [datetime] NULL ,
	[HomeStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[HomeYear] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MortgageStatus] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DepositBoxType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DepositBoxNumber] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastName1] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FirstName1] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SSN1] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BirthDate1] [datetime] NULL ,
	[Type1] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Note1] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastName2] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FirstName2] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SSN2] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BirthDate2] [datetime] NULL ,
	[Type2] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Note2] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastName3] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FirstName3] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SSN3] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BirthDate3] [datetime] NULL ,
	[Type3] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Note3] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DemographicAddress1] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DemographicAddress2] [varchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DemographicCity] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DemographicState] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DemographicZip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IsDemographicAddressForeign] [tinyint] NULL ,
	[Comment1] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment2] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment3] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment4] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment5] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment6] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment7] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment8] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Comment9] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[InformationField1] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[InformationField2] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Auto1Status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Auto1Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Auto2Status] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Auto2Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PhoneVerification] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SelectEmploymentGroup] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DriversLicense] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DriversLicenseState] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RelationshipPricingCurrentPlanCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RelationshipPricingQualifyPlanCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RelationshipPricingRelAcct1] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[RelationshipPricingRelAcct2] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IsPrimarySSN] [tinyint] NULL ,
	[CreditCardLimit] [money] NULL ,
	[UserDate] [datetime] NULL ,
	[ACHMonthlyClearedDebitsPriorMonth] [int] NULL ,
	[ACHMonthlyClearedCreditPriorMonth] [int] NULL ,
	[ACHMonthlyReturnedCountPriorMonth] [int] NULL ,
	[ACHMonthlyPdNegCountPriorMonth] [int] NULL ,
	[ACHMonthlyPdUNCCountPriorMonth] [int] NULL ,
	[ACHMonthlyPdMISCountPriorMonth] [int] NULL ,
	[ACHMonthlyTotalRejectsPriorMonth] [int] NULL ,
	[MemberDormantOn] [datetime] NULL ,
	[ShortName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastStatementOn] [datetime] NULL ,
	[IsOnAnalysis] [tinyint] NULL ,
	[LastCheckCashedOn] [datetime] NULL ,
	[LastNonFinancialTransactionOn] [datetime] NULL ,
	[HomeFaxNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CheckWithdrawlFeeShareType] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CDWithdrawlFeeShareType] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Message] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[SSNCertificateCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ExemptCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CellPhoneNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PhoneVerificationHint] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AccountAnalysisPlanCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastYearYTDDividend] [money] NOT NULL ,
	[LastYearYTDInterest] [money] NOT NULL ,
	[PreviousYTDMortgageInterest] [money] NOT NULL ,
	[BusinessPhoneExtension] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastNonFinancialTransactionTeller] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[HasEFTStatement] [tinyint] NULL ,
	[AccountAnalysisShareDraft] [tinyint] NULL ,
	[HasUserFee01] [tinyint] NULL ,
	[HasUserFee02] [tinyint] NULL ,
	[HasUserFee03] [tinyint] NULL ,
	[HasUserFee04] [tinyint] NULL ,
	[HasUserFee05] [tinyint] NULL ,
	[HasUserFee06] [tinyint] NULL ,
	[HasUserFee07] [tinyint] NULL ,
	[HasUserFee08] [tinyint] NULL ,
	[HasUserFee09] [tinyint] NULL ,
	[HasUserFee10] [tinyint] NULL ,
	[HasUserFee11] [tinyint] NULL ,
	[HasUserFee12] [tinyint] NULL ,
	[HasUserFee13] [tinyint] NULL ,
	[HasUserFee14] [tinyint] NULL ,
	[HasUserFee15] [tinyint] NULL ,
	[HasUserFee16] [tinyint] NULL ,
	[HasUserFee17] [tinyint] NULL ,
	[HasUserFee18] [tinyint] NULL ,
	[HasUserFee19] [tinyint] NULL ,
	[HasUserFee20] [tinyint] NULL ,
	[UserFeeCounter01] [int] NULL ,
	[UserFeeCounter02] [int] NULL ,
	[UserFeeCounter03] [int] NULL ,
	[UserFeeCounter04] [int] NULL ,
	[UserFeeCounter05] [int] NULL ,
	[UserFeeCounter06] [int] NULL ,
	[UserFeeCounter07] [int] NULL ,
	[UserFeeCounter08] [int] NULL ,
	[UserFeeCounter09] [int] NULL ,
	[UserFeeCounter10] [int] NULL ,
	[UserFeeCounter11] [int] NULL ,
	[UserFeeCounter12] [int] NULL ,
	[UserFeeCounter13] [int] NULL ,
	[UserFeeCounter14] [int] NULL ,
	[UserFeeCounter15] [int] NULL ,
	[UserFeeCounter16] [int] NULL ,
	[UserFeeCounter17] [int] NULL ,
	[UserFeeCounter18] [int] NULL ,
	[UserFeeCounter19] [int] NULL ,
	[UserFeeCounter20] [int] NULL ,
	[ExtractForAddressValidation] [tinyint] NULL ,
	[BusinessFax] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[EnrolledRelationshipPricingOn] [datetime] NULL ,
	[AccountAnalysisChargeType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DeceasedOn] [datetime] NULL ,
	[ACHMonthlyClearedDebitsCurrentMonth] [int] NULL ,
	[ACHMonthlyClearedCreditCurrentMonth] [int] NULL ,
	[ACHMonthlyReturnedCountCurrentMonth] [int] NULL ,
	[ACHMonthlyPdNegCountCurrentMonth] [int] NULL ,
	[ACHMonthlyPdUNCCountCurrentMonth] [int] NULL ,
	[ACHMonthlyPdMISCountCurrentMonth] [int] NULL ,
	[ACHMonthlyTotalRejectsCurrentMonth] [int] NULL ,
	[Salutation] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FirstName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MiddleName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Suffix] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[IsPurged] [tinyint] NULL ,
	[DataSource] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[FileDate] [int] NOT NULL ,
	[CreatedOn] [datetime] NOT NULL ,
	CONSTRAINT [PK_Member] PRIMARY KEY  CLUSTERED 
	(
		[MemberNumber]
	)  ON [PRIMARY] 
) ON [PRIMARY]
GO
 CREATE  INDEX [IX_MemberID] ON [legacy].[Member]([MemberID]) ON [PRIMARY]
GO