use DataSoup
go
if exists (select * from dbo.sysobjects where id = object_id(N'[osi].[Colonial07Mortgage]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [osi].[Colonial07Mortgage]
GO
CREATE TABLE [osi].[Colonial07Mortgage] (
	[DiskCode] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CompanyCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ColonialLoanNum] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LienType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[InvestorNum] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CategoyNum] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LoanNum] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL ,
	[PrincipalBalance] [money] NULL ,
	[OriginalTerm] [smallint] NULL ,
	[InterestRate] [float] NULL ,
	[OriginalLoanDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LoanType] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PIConstant] [money] NULL ,
	[OriginalLoanAmount] [money] NULL ,
	[AppraisedValue] [money] NULL ,
	[NextInterestChangeDate] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PIConstantChangeDate] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Filler_1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[InvestorNum2] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CategoryNum2] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Lien2LoanNum] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Lien2PrincipalBalance] [money] NULL ,
	[Lien2LoanTerm] [smallint] NULL ,
	[Lien2InterestRate] [float] NULL ,
	[Lien2OriginalLoanDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Lien2LoanType] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Lien2PIConstant] [money] NULL ,
	[Lien2OriginalLoanAmount] [money] NULL ,
	[Filler_2] [char] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MortgagorShortName] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MortgagorInitials] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MortgagorFullName] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MortgagorTaxID] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CoMortgagorShortName] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CoMortgagorInitials] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CoMortgagorFullName] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[CoMortgagorTaxID] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PropertyNumber] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PropertyDirection] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PropertyStreetName] [char] (22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PropertyCity] [char] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PropertyState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PropertyZip] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[InCareOfLine] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MailingAddress1] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MailingAddress2] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MailingCity] [char] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MailingState] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MailingZip] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DueDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[EscrowBalance] [money] NULL ,
	[EscrowAdvanceBalance] [money] NULL ,
	[TotalPaymentAmount] [money] NULL ,
	[MonthlyEscrowPaid] [money] NULL ,
	[BorrowerServiceCharge] [money] NULL ,
	[SubsidyBuydownAmount] [money] NULL ,
	[MaturityDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Filler_3] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AHLifePremiumAmount1] [smallmoney] NULL ,
	[CoverageType1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AHLifePremiumAmount2] [smallmoney] NULL ,
	[CoverageType2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AHLifePremiumAmount3] [smallmoney] NULL ,
	[CoverageType3] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[AHLifePremiumAmount4] [smallmoney] NULL ,
	[CoverageType4] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[LastPaymentPosted] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[PastDueAmount] [money] NULL ,
	[LateChargeBalanceDue] [smallmoney] NULL ,
	[InspectionFeeBalanceDue] [smallmoney] NULL ,
	[NSFFeesDue] [smallmoney] NULL ,
	[AttorneyFeesDue] [money] NULL ,
	[BillMode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[DateLoanRemoved] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ColonialProductTypeCode] [char] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[MersMinNumber] [char] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BallonDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[YTDPrincipalPaid] [money] NULL ,
	[YTDInterestPaid] [money] NULL ,
	[YTDTaxesPaid] [money] NULL ,
	[YTDHazardInsurancePaid] [money] NULL ,
	[YTDFhaPmiPaid] [money] NULL ,
	[FirstPaymentDueDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Filer_4] [varchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Lien2YTDPrincipalPaid] [money] NULL ,
	[Lien2YTDInterestPaid] [money] NULL ,
	[Lien2FirstPaymentDueDate] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Filler_5] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ProductCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[ClassCode] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[BranchCode] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[GroupCode] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Filler_6] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
	[Period] [int] NOT NULL ,
	CONSTRAINT [PK_Colonial07Mortgage] PRIMARY KEY  CLUSTERED 
	(
		[Period],
		[LoanNum]
	) WITH  FILLFACTOR = 90  ON [PRIMARY] 
) ON [PRIMARY]
GO
 CREATE  INDEX [IX_LastPaymentPosted] ON [osi].[Colonial07Mortgage]([LastPaymentPosted]) ON [PRIMARY]
GO
setuser N'osi'
GO
EXEC sp_bindefault N'[dbo].[df_PeriodCurrent]', N'[Colonial07Mortgage].[Period]'
GO
setuser
GO