CREATE TABLE [customers].[PropertyHistory]
(
[IDSeq] [bigint] NOT NULL IDENTITY(1, 1),
[PropertyIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[PriceTypeCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL CONSTRAINT [DF_PropertyHistoryLog_PriceTypeCode] DEFAULT ('Normal'),
[ThresholdOverrideFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_ThresholdOverrideFlag] DEFAULT ((0)),
[SiteMasterID] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Number] [varchar] (12) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Name] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[PMCIDSeq] [char] (11) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[OwnerIDSeq] [char] (11) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[OwnerName] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL CONSTRAINT [DF_PropertyHistoryLog_OwnerName] DEFAULT (''),
[Units] [int] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_Units] DEFAULT ((0)),
[Beds] [int] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_Beds] DEFAULT ((0)),
[PPUPercentage] [int] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_PPUPercentage] DEFAULT ((100)),
[YearBuilt] [smallint] NULL,
[SubPropertyFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_SubPropertyHistoryFlag] DEFAULT ((0)),
[ConventionalFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_ConventionalFlag] DEFAULT ((1)),
[StudentLivingFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_StudentLiving] DEFAULT ((0)),
[HUDFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_HUDFlag] DEFAULT ((0)),
[RHSFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_RHSFlag] DEFAULT ((0)),
[TaxCreditFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_TaxCreditFlag] DEFAULT ((0)),
[CreatedBy] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ModifiedBy] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[CreatedDate] [datetime] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_CreatedDate] DEFAULT (getdate()),
[ModifiedDate] [datetime] NULL CONSTRAINT [DF_PropertyHistoryLog_ModifiedDate] DEFAULT (getdate()),
[SiebelRowID] [varchar] (15) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[PriceTerm] [int] NULL,
[SiebelID] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StatusTypeCode] [varchar] (5) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL CONSTRAINT [DF_PropertyHistoryLog_StatusTypeCode] DEFAULT ('ACTIV'),
[TransferPMCIDSeq] [char] (11) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TransferDate] [datetime] NULL,
[QuotableUnits] [int] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_QuotableUnits] DEFAULT ((0)),
[QuotableBeds] [int] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_QuotableBeds] DEFAULT ((0)),
[LegacyRegistrationCode] [varchar] (4) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Phase] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL CONSTRAINT [DF_CUSTOMERS_PropertyHistory_Phase] DEFAULT (''),
[CustomBundlesProductBreakDownTypeCode] [varchar] (4) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL CONSTRAINT [DF_PropertyHistoryLog_CustomBundlesProductBreakDownTypeCode] DEFAULT ('DEFC'),
[EpicorCustomerCode] [varchar] (8) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[VendorFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_VendorFlag] DEFAULT ((0)),
[SystemLogDate] [datetime] NOT NULL CONSTRAINT [DF_PropertyHistoryLog_LogDate] DEFAULT (getdate()),
[RECORDSTAMP] [timestamp] NOT NULL,
[ModifiedByIDSeq] [bigint] NULL,
[SeparateInvoiceByFamilyFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistory_SeparateInvoiceByFamilyFlag] DEFAULT ((0)),
[SendInvoiceToClientFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistory_SendInvoiceToClientFlag] DEFAULT ((1)),
[RetailFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistory_RetailFlag] DEFAULT ((0)),
[GSAEntityFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistory_GSAEntityFlag] DEFAULT ((0)),
[CreatedByIDSeq] [bigint] NOT NULL CONSTRAINT [DF_PropertyHistory_CreatedByIDSeq] DEFAULT ((-1)),
[MilitaryPrivatizedFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistory_MilitaryPrivatizedFlag] DEFAULT ((0)),
[SeniorLivingFlag] [bit] NOT NULL CONSTRAINT [DF_PropertyHistory_SeniorLivingFlag] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [customers].[PropertyHistory] ADD CONSTRAINT [PK_PropertyHistoryLog] PRIMARY KEY CLUSTERED  ([IDSeq]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IXN_PropertyHistory_RECORDSTAMP] ON [customers].[PropertyHistory] ([RECORDSTAMP]) ON [PRIMARY]
GO
