CREATE TABLE [customers].[MigrationClientInfo]
(
[ImportID] [bigint] NOT NULL IDENTITY(1, 1),
[SystemID] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Name] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Type] [varchar] (12) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ClientType] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[PMCName] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[PMCSystemID] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[OneSiteID] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[PMCOneSiteID] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[OMSID] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[OMSParentID] [varchar] (15) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[PropertyStatus] [varchar] (15) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Units] [int] NULL,
[Beds] [int] NULL,
[StreetContactName] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetPhoneNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetFaxNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Owner] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[URL] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[SyncStartMonth] [int] NULL,
[ExpandCustomBundle] [char] (4) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[PrintSeparateInvoice] [int] NULL,
[InvoiceDeliveryOption] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetAddressLine1] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetAddressLine2] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetCity] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetState] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetZip] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[StreetCountry] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingSameAsPmc] [bit] NULL,
[BillingAddressLine1] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingAddressLine2] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingCity] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingState] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingZip] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingEmail] [varchar] (150) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingCountry] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingAttentionTo] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShippingSameAsPMC] [bit] NULL,
[ShipAddressLine1] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShipAddressLine2] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShipCity] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShipState] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShipZip] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShipCountry] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShippingAttentionTo] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillPMC] [bit] NULL,
[Diff] [int] NULL,
[NameDiff] [int] NULL,
[AddrDiff] [int] NULL,
[CityDiff] [int] NULL,
[StateDiff] [int] NULL,
[ZipDiff] [int] NULL,
[PhoneDiff] [int] NULL,
[UnitsDiff] [int] NULL,
[UnitsCompare] [int] NULL,
[Message] [varchar] (1000) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ValidateStreet] [xml] NULL,
[ValidateBilling] [xml] NULL,
[ValidateShipping] [xml] NULL,
[ImportDate] [datetime] NULL,
[ImportClientID] [int] NULL,
[fkClientID] [int] NULL,
[ExceptionID] [bit] NULL,
[Batch] [int] NULL,
[StreetCellNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShippingPhoneNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShippingFaxNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ShippingCellNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingPhoneNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingFaxNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[BillingCellNumber] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[CustomerType] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[GovtEntity] [bit] NULL,
[SiteType] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [customers].[MigrationClientInfo] ADD CONSTRAINT [PK_MigrationClientInfo] PRIMARY KEY CLUSTERED  ([ImportID]) ON [PRIMARY]
GO
