CREATE TABLE [docs].[DocumentMigrationStaging]
(
[IDSeq] [int] NOT NULL IDENTITY(1, 1),
[CompanyName] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[SitemasterID] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[addressline1] [varchar] (200) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[addressline2] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[city] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[state] [char] (2) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[zip] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[DocumentTypeCode] [varchar] (5) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[DocumentLevelCode] [varchar] (5) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[Name] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[Description] [varchar] (4000) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[CompanyIDSeq] [varchar] (11) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[PropertyIDSeq] [varchar] (11) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[AccountIDSeq] [varchar] (11) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[FamilyCode] [char] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[AgreementAddendum] [varchar] (6000) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[AgreementExecutedFlag] [bit] NOT NULL,
[ActiveFlag] [bit] NOT NULL,
[DocumentPath] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[AttachmentFlag] [bit] NOT NULL,
[AgreementSignedDate] [datetime] NULL,
[AgreementSentDate] [datetime] NULL,
[CreatedBy] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ModifiedBy] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[CreatedDate] [datetime] NOT NULL,
[ModifiedDate] [datetime] NULL,
[PrintOnInvoiceFlag] [bit] NOT NULL,
[NewCompanyIDSeq] [varchar] (11) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[NewDocumentIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[NewContractIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ErrorMessage] [varchar] (max) COLLATE SQL_Latin1_General_CP850_CI_AI NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
