CREATE TABLE [invoices].[CreditMemoItem]
(
[IDSeq] [bigint] NOT NULL IDENTITY(1, 1),
[CreditMemoIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[InvoiceIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[InvoiceGroupIDSeq] [bigint] NOT NULL,
[CustomBundleNameEnabledFlag] [bit] NOT NULL CONSTRAINT [DF_CreditMemoItem_CustomBundleNameEnabledFlag] DEFAULT ((0)),
[InvoiceItemIDSeq] [bigint] NOT NULL,
[UnitCreditAmount] [money] NOT NULL CONSTRAINT [DF_CreditMemoItem_UnitCreditAmount] DEFAULT ((0)),
[EffectiveQuantity] [decimal] (18, 5) NOT NULL CONSTRAINT [DF_InvoiceItemCredit_Quantity] DEFAULT ((0.00)),
[ExtCreditAmount] [money] NOT NULL CONSTRAINT [DF_CreditMemoItem_ExtCreditAmount] DEFAULT ((0)),
[DiscountCreditAmount] [money] NOT NULL CONSTRAINT [DF_CreditMemoItem_DiscountCreditAmount] DEFAULT ((0)),
[TaxPercent] [numeric] (30, 5) NOT NULL CONSTRAINT [DF_InvoiceItemCredit_TaxPercent] DEFAULT ((0.00)),
[TaxAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItemCredit_TaxAmount] DEFAULT ((0)),
[NetCreditAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItemCredit_NetCreditAmount] DEFAULT ((0)),
[RevenueTierCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RevenueAccountCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[DeferredRevenueAccountCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RevenueRecognitionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__3E73D64A] DEFAULT ((0.00)),
[TaxwarePrimaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__3F67FA83] DEFAULT ((0)),
[TaxwareSecondaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__405C1EBC] DEFAULT ((0.00)),
[TaxwareSecondaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__415042F5] DEFAULT ((0)),
[TaxwarePrimaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4244672E] DEFAULT ((0.00)),
[TaxwarePrimaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__43388B67] DEFAULT ((0)),
[TaxwareSecondaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__442CAFA0] DEFAULT ((0.00)),
[TaxwareSecondaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4520D3D9] DEFAULT ((0)),
[TaxwarePrimaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4614F812] DEFAULT ((0.00)),
[TaxwarePrimaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__47091C4B] DEFAULT ((0)),
[TaxwareSecondaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__47FD4084] DEFAULT ((0.00)),
[TaxwareSecondaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__48F164BD] DEFAULT ((0)),
[TaxwarePrimaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__49E588F6] DEFAULT ((0)),
[TaxwareSecondaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4AD9AD2F] DEFAULT ((0)),
[TaxwarePrimaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4BCDD168] DEFAULT ((0)),
[TaxwareSecondaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4CC1F5A1] DEFAULT ((0)),
[TaxwarePrimaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4DB619DA] DEFAULT ((0)),
[TaxwareSecondaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4EAA3E13] DEFAULT ((0)),
[TaxwarePrimaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareCallOverrideFlag] [bit] NOT NULL CONSTRAINT [DF__CreditMem__Taxwa__4F9E624C] DEFAULT ((0)),
[ShippingAndHandlingCreditAmount] [money] NOT NULL CONSTRAINT [DF_CreditmemoItem_ShippingAndHandlingCreditAmount] DEFAULT ((0.00)),
[TaxwarePrimaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[CreditMemoReversalFlag] [int] NOT NULL CONSTRAINT [DF_CreditMemoItem_CreditMemoReversalFlag] DEFAULT ((0)),
[ApplyToCreditMemoIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[DefaultTaxwareCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[UnitOfMeasure] [decimal] (18, 5) NOT NULL CONSTRAINT [DF_CreditMemoItem_UnitOfMeasure] DEFAULT ((0.00)),
[RECORDSTAMP] [timestamp] NOT NULL,
[RECALCNeeded] [bit] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__23AECA28] DEFAULT ((0)),
[RECALCComplete] [bit] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__24A2EE61] DEFAULT ((0)),
[RECALCTaxPercent] [numeric] (30, 5) NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2597129A] DEFAULT ((0.00)),
[RECALCTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__268B36D3] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__RECAL__277F5B0C] DEFAULT ((0.00)),
[RECALCTaxwarePrimaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__28737F45] DEFAULT ((0)),
[RECALCTaxwareSecondaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2967A37E] DEFAULT ((0.00)),
[RECALCTaxwareSecondaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2A5BC7B7] DEFAULT ((0)),
[RECALCTaxwarePrimaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2B4FEBF0] DEFAULT ((0.00)),
[RECALCTaxwarePrimaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2C441029] DEFAULT ((0)),
[RECALCTaxwareSecondaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2D383462] DEFAULT ((0.00)),
[RECALCTaxwareSecondaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2E2C589B] DEFAULT ((0)),
[RECALCTaxwarePrimaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__RECAL__2F207CD4] DEFAULT ((0.00)),
[RECALCTaxwarePrimaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__3014A10D] DEFAULT ((0)),
[RECALCTaxwareSecondaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__CreditMem__RECAL__3108C546] DEFAULT ((0.00)),
[RECALCTaxwareSecondaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__31FCE97F] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__32F10DB8] DEFAULT ((0)),
[RECALCTaxwareSecondaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__33E531F1] DEFAULT ((0)),
[RECALCTaxwarePrimaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__34D9562A] DEFAULT ((0)),
[RECALCTaxwareSecondaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__35CD7A63] DEFAULT ((0)),
[RECALCTaxwarePrimaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__36C19E9C] DEFAULT ((0)),
[RECALCTaxwareSecondaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__37B5C2D5] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareCallOverrideFlag] [bit] NOT NULL CONSTRAINT [DF__CreditMem__RECAL__38A9E70E] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareErrorMessage] [varchar] (1000) COLLATE SQL_Latin1_General_CP850_CI_AI NULL CONSTRAINT [DF__CreditMem__RECAL__399E0B47] DEFAULT (''),
[RECALCTaxwareErrorFlag] [bit] NULL CONSTRAINT [DF__CreditMem__RECAL__3A922F80] DEFAULT ((0)),
[CreatedDate] [datetime] NOT NULL CONSTRAINT [DF_CreditMemoItem_CreatedDate] DEFAULT (getdate()),
[CreatedByIDSeq] [bigint] NOT NULL CONSTRAINT [DF_CreditMemoItem_CreatedByIDSeq] DEFAULT ((-1)),
[ModifiedDate] [datetime] NULL,
[ModifiedByIDSeq] [bigint] NULL,
[SystemLogDate] [datetime] NOT NULL CONSTRAINT [DF_CreditMemoItem_SystemLogDate] DEFAULT (getdate()),
[TaxwareGSTCountryTaxAmount] [money] NULL,
[TaxwareGSTCountryTaxPercent] [numeric] (18, 5) NULL,
[TaxwarePSTStateTaxAmount] [money] NULL,
[TaxwarePSTStateTaxPercent] [numeric] (18, 5) NULL,
[RECALCTaxwareGSTCountryTaxAmount] [money] NULL,
[RECALCTaxwareGSTCountryTaxPercent] [numeric] (18, 5) NULL,
[RECALCTaxwarePSTStateTaxAmount] [money] NULL,
[RECALCTaxwarePSTStateTaxPercent] [numeric] (18, 5) NULL
) ON [PRIMARY]
GO
ALTER TABLE [invoices].[CreditMemoItem] ADD CONSTRAINT [PK_CreditMemoItem] PRIMARY KEY CLUSTERED  ([IDSeq] DESC) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_CreditMemoItem_CreditMemoIDSeq] ON [invoices].[CreditMemoItem] ([CreditMemoIDSeq] DESC) INCLUDE ([IDSeq], [InvoiceGroupIDSeq], [InvoiceIDSeq], [InvoiceItemIDSeq]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_CreditMemoItem_CreditMemo] ON [invoices].[CreditMemoItem] ([CreditMemoIDSeq] DESC, [InvoiceIDSeq] DESC) INCLUDE ([IDSeq], [InvoiceGroupIDSeq], [InvoiceItemIDSeq]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_CreditMemoItem_CreditMemo_ItemsID] ON [invoices].[CreditMemoItem] ([CreditMemoIDSeq] DESC, [InvoiceIDSeq] DESC, [InvoiceItemIDSeq] DESC, [InvoiceGroupIDSeq] DESC) INCLUDE ([IDSeq]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_CreditMemoItem_InvoiceIDSeq] ON [invoices].[CreditMemoItem] ([InvoiceIDSeq]) INCLUDE ([CreditMemoIDSeq]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_CreditMemoItem_InvoiceItemIDSeq] ON [invoices].[CreditMemoItem] ([InvoiceItemIDSeq]) INCLUDE ([CreditMemoIDSeq], [InvoiceIDSeq]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IXN_CreditMemoItem_RECORDSTAMP] ON [invoices].[CreditMemoItem] ([RECORDSTAMP]) ON [PRIMARY]
GO
ALTER TABLE [invoices].[CreditMemoItem] WITH NOCHECK ADD CONSTRAINT [CreditMemoItem_has_CreditMemo] FOREIGN KEY ([CreditMemoIDSeq]) REFERENCES [invoices].[CreditMemo] ([CreditMemoIDSeq])
GO
ALTER TABLE [invoices].[CreditMemoItem] WITH NOCHECK ADD CONSTRAINT [CreditMemoItem_has_InvoiceItem] FOREIGN KEY ([InvoiceItemIDSeq]) REFERENCES [invoices].[InvoiceItem] ([IDSeq])
GO
