CREATE TABLE [invoices].[InvoiceItem]
(
[IDSeq] [bigint] NOT NULL IDENTITY(1, 1),
[InvoiceIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[InvoiceGroupIDSeq] [bigint] NOT NULL,
[OrderIDSeq] [varchar] (22) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[OrderGroupIDSeq] [bigint] NOT NULL CONSTRAINT [DF_InvoiceItem_OrderGroupIDSeq] DEFAULT ((0)),
[OrderItemIDSeq] [bigint] NOT NULL CONSTRAINT [DF_InvoiceItem_OrderItemIDSeq] DEFAULT ((0)),
[OrderItemTransactionIDseq] [bigint] NULL,
[OrderItemRenewalCount] [int] NOT NULL CONSTRAINT [DF_InvoiceItem_OrderItemRenewalCount] DEFAULT ((0)),
[ProductCode] [varchar] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[ChargeTypeCode] [char] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[FrequencyCode] [char] (6) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[MeasureCode] [char] (6) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[PriceVersion] [numeric] (18, 0) NULL,
[Units] [int] NULL,
[Beds] [int] NULL,
[PPUPercentage] [int] NULL,
[Quantity] [decimal] (18, 3) NOT NULL CONSTRAINT [DF_InvoiceItem_Quantity] DEFAULT ((1)),
[AllowCreditFlag] [bit] NOT NULL CONSTRAINT [DF_InvoiceItem_AllowCreditFlag] DEFAULT ((1)),
[ChargeAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItem_ChargeAmount] DEFAULT ((0)),
[EffectiveQuantity] [decimal] (18, 6) NOT NULL CONSTRAINT [DF_InvoiceItem_EffectiveQuantity] DEFAULT ((0.00)),
[ExtChargeAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItem_ExtChargeAmount] DEFAULT ((0)),
[DiscountAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItem_DiscountAmount] DEFAULT ((0)),
[CreditAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItem_CreditAmount] DEFAULT ((0)),
[TaxPercent] [numeric] (30, 5) NOT NULL CONSTRAINT [DF_InvoiceItem_TaxPercent] DEFAULT ((0.00)),
[TaxAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItem_TaxAmount] DEFAULT ((0)),
[NetChargeAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItem_NetChargeAmount] DEFAULT ((0)),
[BillingPeriodFromDate] [datetime] NOT NULL,
[BillingPeriodToDate] [datetime] NULL,
[TransactionItemName] [varchar] (300) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ServiceCode] [varchar] (6) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TransactionDate] [datetime] NULL,
[RevenueTierCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RevenueAccountCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[DeferredRevenueAccountCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RevenueRecognitionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__50928685] DEFAULT ((0.00)),
[TaxwarePrimaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5186AABE] DEFAULT ((0)),
[TaxwareSecondaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__527ACEF7] DEFAULT ((0.00)),
[TaxwareSecondaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__536EF330] DEFAULT ((0)),
[TaxwarePrimaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__54631769] DEFAULT ((0.00)),
[TaxwarePrimaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__55573BA2] DEFAULT ((0)),
[TaxwareSecondaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__564B5FDB] DEFAULT ((0.00)),
[TaxwareSecondaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__573F8414] DEFAULT ((0)),
[TaxwarePrimaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5833A84D] DEFAULT ((0.00)),
[TaxwarePrimaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5927CC86] DEFAULT ((0)),
[TaxwareSecondaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5A1BF0BF] DEFAULT ((0.00)),
[TaxwareSecondaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5B1014F8] DEFAULT ((0)),
[TaxwarePrimaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5C043931] DEFAULT ((0)),
[TaxwareSecondaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5CF85D6A] DEFAULT ((0)),
[TaxwarePrimaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5DEC81A3] DEFAULT ((0)),
[TaxwareSecondaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5EE0A5DC] DEFAULT ((0)),
[TaxwarePrimaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__5FD4CA15] DEFAULT ((0)),
[TaxwareSecondaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__60C8EE4E] DEFAULT ((0)),
[TaxwarePrimaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareCallOverrideFlag] [bit] NOT NULL CONSTRAINT [DF__InvoiceIt__Taxwa__61BD1287] DEFAULT ((0)),
[ShippingAndHandlingAmount] [money] NOT NULL CONSTRAINT [DF_InvoiceItem_ShippingAndHandlingAmount] DEFAULT ((0.00)),
[TaxwarePrimaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwarePrimaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareSecondaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[CredtCardPricingPercentage] [numeric] (30, 3) NOT NULL CONSTRAINT [DF_InvoiceItem_CredtCardPricingPercentage] DEFAULT ((0.000)),
[CreatedDate] [datetime] NOT NULL CONSTRAINT [DF_InvoiceItem_CreatedDate] DEFAULT (getdate()),
[DefaultTaxwareCode] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[UnitOfMeasure] [decimal] (18, 5) NOT NULL CONSTRAINT [DF_InvoiceItem_UnitOfMeasure] DEFAULT ((0.00)),
[ReportingTypeCode] [varchar] (4) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[PricingTiers] [int] NOT NULL CONSTRAINT [DF_InvoiceItem_PricingTiers] DEFAULT ((1)),
[RECORDSTAMP] [timestamp] NOT NULL,
[TaxableAddressLine1] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxableAddressLine2] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxableCity] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxableState] [varchar] (2) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxableZip] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxableCountryCode] [varchar] (10) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Billtoaddresstypecode] [varchar] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxableCounty] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxableAddressTypeCode] [varchar] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCNeeded] [bit] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__0BD74097] DEFAULT ((0)),
[RECALCComplete] [bit] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__0CCB64D0] DEFAULT ((0)),
[RECALCTaxPercent] [numeric] (30, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__0DBF8909] DEFAULT ((0.00)),
[RECALCTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__0EB3AD42] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__0FA7D17B] DEFAULT ((0.00)),
[RECALCTaxwarePrimaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__109BF5B4] DEFAULT ((0)),
[RECALCTaxwareSecondaryStateTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__119019ED] DEFAULT ((0.00)),
[RECALCTaxwareSecondaryStateTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__12843E26] DEFAULT ((0)),
[RECALCTaxwarePrimaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1378625F] DEFAULT ((0.00)),
[RECALCTaxwarePrimaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__146C8698] DEFAULT ((0)),
[RECALCTaxwareSecondaryCityTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1560AAD1] DEFAULT ((0.00)),
[RECALCTaxwareSecondaryCityTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1654CF0A] DEFAULT ((0)),
[RECALCTaxwarePrimaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1748F343] DEFAULT ((0.00)),
[RECALCTaxwarePrimaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__183D177C] DEFAULT ((0)),
[RECALCTaxwareSecondaryCountyTaxPercent] [numeric] (18, 5) NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__19313BB5] DEFAULT ((0.00)),
[RECALCTaxwareSecondaryCountyTaxAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1A255FEE] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1B198427] DEFAULT ((0)),
[RECALCTaxwareSecondaryStateTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1C0DA860] DEFAULT ((0)),
[RECALCTaxwarePrimaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1D01CC99] DEFAULT ((0)),
[RECALCTaxwareSecondaryCityTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1DF5F0D2] DEFAULT ((0)),
[RECALCTaxwarePrimaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1EEA150B] DEFAULT ((0)),
[RECALCTaxwareSecondaryCountyTaxBasisAmount] [money] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__1FDE3944] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryStateJurisdictionZipCode] [varchar] (20) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCityJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCountyJurisdiction] [varchar] (70) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareCallOverrideFlag] [bit] NOT NULL CONSTRAINT [DF__InvoiceIt__RECAL__20D25D7D] DEFAULT ((0)),
[RECALCTaxwarePrimaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwarePrimaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryStateSalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCountySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareSecondaryCitySalesUseTaxIndicator] [char] (1) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RECALCTaxwareErrorMessage] [varchar] (1000) COLLATE SQL_Latin1_General_CP850_CI_AI NULL CONSTRAINT [DF__InvoiceIt__RECAL__21C681B6] DEFAULT (''),
[RECALCTaxwareErrorFlag] [bit] NULL CONSTRAINT [DF__InvoiceIt__RECAL__22BAA5EF] DEFAULT ((0)),
[CreatedByIDSeq] [bigint] NOT NULL CONSTRAINT [DF_InvoiceItem_CreatedByIDSeq] DEFAULT ((-1)),
[ModifiedDate] [datetime] NULL,
[ModifiedByIDSeq] [bigint] NULL,
[SystemLogDate] [datetime] NOT NULL CONSTRAINT [DF_InvoiceItem_SystemLogDate] DEFAULT (getdate()),
[BillToDeliveryOptionCode] [varchar] (5) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[TaxwareGSTCountryTaxAmount] [money] NULL,
[TaxwareGSTCountryTaxPercent] [numeric] (18, 5) NULL,
[TaxwarePSTStateTaxAmount] [money] NULL,
[TaxwarePSTStateTaxPercent] [numeric] (18, 5) NULL,
[RECALCTaxwareGSTCountryTaxAmount] [money] NULL,
[RECALCTaxwareGSTCountryTaxPercent] [numeric] (18, 5) NULL,
[RECALCTaxwarePSTStateTaxAmount] [money] NULL,
[RECALCTaxwarePSTStateTaxPercent] [numeric] (18, 5) NULL
) ON [PRIMARY]
GO
ALTER TABLE [invoices].[InvoiceItem] ADD CONSTRAINT [PK_InvoiceItem] PRIMARY KEY CLUSTERED  ([IDSeq] DESC) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_Invoices_Invoiceitem_ProductCode] ON [invoices].[InvoiceItem] ([Billtoaddresstypecode], [BillToDeliveryOptionCode], [ChargeTypeCode], [ReportingTypeCode], [MeasureCode], [FrequencyCode], [ProductCode]) INCLUDE ([IDSeq], [InvoiceGroupIDSeq], [InvoiceIDSeq], [OrderGroupIDSeq], [OrderItemIDSeq], [OrderItemTransactionIDseq]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_Invoices_Invoiceitem_InvoiceIDseq] ON [invoices].[InvoiceItem] ([InvoiceIDSeq] DESC, [InvoiceGroupIDSeq] DESC, [ProductCode], [Billtoaddresstypecode], [BillToDeliveryOptionCode]) INCLUDE ([ChargeTypeCode], [FrequencyCode], [IDSeq], [MeasureCode], [OrderGroupIDSeq], [OrderIDSeq], [OrderItemIDSeq], [OrderItemTransactionIDseq], [PriceVersion]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [INCX_Invoices_Invoiceitem_OrderIDseq] ON [invoices].[InvoiceItem] ([OrderIDSeq] DESC, [OrderGroupIDSeq] DESC, [OrderItemIDSeq] DESC, [OrderItemTransactionIDseq] DESC, [ProductCode], [Billtoaddresstypecode], [BillToDeliveryOptionCode]) INCLUDE ([ChargeTypeCode], [FrequencyCode], [IDSeq], [InvoiceGroupIDSeq], [InvoiceIDSeq], [MeasureCode], [PriceVersion]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IXN_InvoiceItem_RECORDSTAMP] ON [invoices].[InvoiceItem] ([RECORDSTAMP]) ON [PRIMARY]
GO
ALTER TABLE [invoices].[InvoiceItem] WITH NOCHECK ADD CONSTRAINT [InvoiceItem_has_InvoiceGroup] FOREIGN KEY ([InvoiceGroupIDSeq]) REFERENCES [invoices].[InvoiceGroup] ([IDSeq])
GO
ALTER TABLE [invoices].[InvoiceItem] WITH NOCHECK ADD CONSTRAINT [InvoiceItem_has_Invoice] FOREIGN KEY ([InvoiceIDSeq]) REFERENCES [invoices].[Invoice] ([InvoiceIDSeq])
GO
ALTER TABLE [invoices].[InvoiceItem] WITH NOCHECK ADD CONSTRAINT [InvoiceItem_has_ServiceType] FOREIGN KEY ([ServiceCode]) REFERENCES [invoices].[ServiceType] ([Code])
GO
