CREATE TABLE [products].[PRODUCT_BEFOREUPDATES]
(
[Code] [char] (30) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[PriceVersion] [numeric] (18, 0) NOT NULL,
[PlatformCode] [char] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[FamilyCode] [char] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[CategoryCode] [char] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[ProductTypeCode] [char] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ItemCode] [char] (15) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[SortSeq] [int] NOT NULL,
[Name] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[DisplayName] [varchar] (100) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[Description] [varchar] (255) COLLATE SQL_Latin1_General_CP850_CI_AI NOT NULL,
[OptionFlag] [bit] NOT NULL,
[SOCFlag] [int] NOT NULL,
[DisabledFlag] [bit] NOT NULL,
[StartDate] [datetime] NOT NULL,
[EndDate] [datetime] NULL,
[CreatedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[ModifiedBy] [varchar] (50) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[CreateDate] [datetime] NOT NULL,
[ModifyDate] [datetime] NOT NULL,
[PriceCapEnabledFlag] [bit] NOT NULL,
[PendingApprovalFlag] [bit] NOT NULL,
[ExcludeForBookingsFlag] [bit] NOT NULL,
[stockbundleflag] [bit] NOT NULL,
[LegacyProductCode] [varchar] (6) COLLATE SQL_Latin1_General_CP850_CI_AI NULL,
[RegAdminProductFlag] [bit] NOT NULL,
[ReportPrimaryProductFlag] [bit] NOT NULL,
[MPFPublicationFlag] [bit] NOT NULL,
[RECORDSTAMP] [timestamp] NOT NULL,
[StockBundleIdentifierCode] [varchar] (3) COLLATE SQL_Latin1_General_CP850_CI_AI NULL
) ON [PRIMARY]
GO
